AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon RDS MySQL Database

Parameters:
  VPCName:
    Type: String
  InstanceType:
    Type: String
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String
  DBUsername:
    Type: String
    NoEcho: true
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  MyDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties: 
      DBSubnetGroupDescription: "Subnet group for RDS instance"
      SubnetIds: 
        - !ImportValue 
          Fn::Sub: "${VPCName}-private-subnet-1-id"
        - !ImportValue 
          Fn::Sub: "${VPCName}-private-subnet-2-id"

  MyDBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow inbound traffic to RDS
      VpcId: !ImportValue 
        Fn::Sub: "${VPCName}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306 
          ToPort: 3306
          CidrIp: 0.0.0.0/0 # Replace with a more restrictive CIDR range in production

  MyRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: MyRDSInstance
      AllocatedStorage: 20 
      DBInstanceClass: !Ref InstanceType
      Engine: mysql
      EngineVersion: '8.0'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      VPCSecurityGroups:
        - !Ref MyDBSecurityGroup
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      BackupRetentionPeriod: 7
      DeletionPolicy: Snapshot
      DBName: MyDatabase # Initial database name

  MyDBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: "Parameter group for MySQL 8.0"
      Family: mysql8.0
      Parameters:
        character_set_database: utf8mb4
        collation_server: utf8mb4_unicode_ci

  MyDBOptionGroup:
    Type: 'AWS::RDS::OptionGroup'
    Properties:
      EngineName: mysql
      MajorEngineVersion: '8.0'
      OptionGroupDescription: "Option group for MySQL 8.0"
      OptionConfigurations:
        - OptionName: "MEMCACHED"
          Port: 11211

Outputs:
  RDSInstanceEndpoint:
    Description: The endpoint of the RDS instance
    Value: !GetAtt MyRDSInstance.Endpoint.Address

  RDSInstancePort:
    Description: The port of the RDS instance
    Value: !GetAtt MyRDSInstance.Endpoint.Port
