AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for VPC in different environments

Parameters:
  EnvironmentName:
    Type: String
    Description: The environment name (dev, qa, prod)
  VpcCIDR:
    Type: String
    Description: The CIDR block for the VPC
  PublicSubnet1CIDR:
    Type: String
    Description: The CIDR block for the first public subnet
  PublicSubnet2CIDR:
    Type: String
    Description: The CIDR block for the second public subnet
  PrivateSubnet1CIDR:
    Type: String
    Description: The CIDR block for the first private subnet
  PrivateSubnet2CIDR:
    Type: String
    Description: The CIDR block for the second private subnet
  AvailabilityZone1:
    Type: String
    Description: The first availability zone
  AvailabilityZone2:
    Type: String
    Description: The second availability zone
  InstanceType:
    Type: String
    Description: The EC2 instance type
  KeyName:
    Type: String
    Description: The name of the EC2 key pair
  SSHLocation:
    Type: String
    Description: The IP address range that can be used to SSH to the EC2 instances

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-bucket/vpc-stack.yaml'
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        EnvironmentName: !Ref EnvironmentName
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SSHLocation: !Ref SSHLocation
