AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:

  VPCName:
    Type: String

Resources:

  NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/vpc.yaml'
      Parameters:
        VPCName: !Ref VPCName
