AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:

  VpcName:
    Type: String

Resources:

  NestedVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/my-demo-s3-bucket-test-project-11/vpc.yaml'
      Parameters:
        VpcName: !Ref VpcName
