AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack template

Parameters:

  VpcName:
    Type: String

Resources:

  NestedVPCStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc.yml'
      Parameters:
        VpcName: !Ref VpcName
