AWSTemplateFormatVersion: "2010-09-09"

Resources:
  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CloudFormationRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "CloudFormationPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeInstanceStatus"
                  - "ec2:DescribeImages"
                  - "ec2:DescribeKeyPairs"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcs"
                  - "ec2:RunInstances"
                  - "ec2:TerminateInstances"
                  - "iam:PassRole"
                  - "cloudformation:CreateStack"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:DeleteStack"
                Resource: "*"

Outputs:
  CloudFormationRole:
    Description: "ARN of the CloudFormation execution role"
    Value: !GetAtt CloudFormationRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CloudFormationRoleArn"
